spring:
  datasource:
    url: ${db_url_dev}
    username: ${db_user_dev}
    password: ${db_password_dev}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      host : ${redis_host_dev}
      port : ${redis_port_dev}
      password : ${redis_password_dev}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.hibernate.SQL: debug